---
  - name: "{{ playbook_name }}"
    hosts: "{{ droplets }}" 
    gather_facts: "{{ facts }}"
    vars_files: "variables/package_vars.yaml"
    tasks:
      - name:  install {{ packages }} on CentOS
        yum:
          name:  "{{ list_of_packages }}"
          state: latest
        when: ansible_distribution == "CentOS"

      - name:  install {{ packages }} on Ubuntu
        apt:
          name:  "{{ list_of_packages }}"
          state: latest
        when: ansible_facts['distribution'] == "Ubuntu" 

      - name: run a task
        shell:
          cmd: "{{ custom_cmd }}"        