---
  - name: "{{ playbook_name }}"
    hosts: "{{ servers }}"
    gather_facts: "{{ facts }}"
    vars_files: 
      - "variables/useradd_sudoers_play_vars.yaml"
      - "variables/useradd_sudoers_tasks_vars.yaml"
      - "variables/users.yaml"      
    tasks:
      - name: ping hosts 
        ping:

      - name:   add {{ usr_name }} on CentOS
        when: ansible_facts['distribution'] == "CentOS"
        user:
          name: "{{ item.name }}"
          state: present
          generate_ssh_key: "{{ ssh_keygen }}" 
        with_items: "{{ user_names }}" 

      - name: add {{ usr_name }} on Ubuntu
        when: ansible_facts['distribution'] == "Ubuntu"
        user:
          name: "{{ item.name }}"
          state: present
          generate_ssh_key: "{{ ssh_keygen }}" 
        with_items: "{{ user_names }}" 
      
      - name: "{{ add_ans_sudo }}"
        when: ansible_facts['distribution'] == "Ubuntu"
        user: 
          name: ansible
          groups: "{{ ubuntu_sudo_grp }}"
          append: "{{ append_to_sudoers_grp }}"

      - name: "{{ add_ans_sudo }}"
        when: ansible_facts['distribution'] ==  "CentOS" 
        user: 
          name: ansible
          groups: "{{ centos_wheel_grp }}"
          append: "{{ append_to_sudoers_grp }}"

      - name: "{{ ssh_key_check }}"
        authorized_key:
          user: root 
          key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
          state: present

      - name: "{{ ubuntu_cp_ssh_key }}"
        copy:
          src: "/root/.ssh/id_rsa.pub"
          dest: "/home/ansible/.ssh/authorized_keys"  
        when: ansible_facts['distribution'] == "Ubuntu"

      - name: "{{ ubuntu_cp_ssh_key }}"
        copy:
          src: "/root/.ssh/id_rsa.pub"
          dest: "/home/ansible/.ssh/authorized_keys"  
        when: ansible_facts['distribution'] ==  "CentOS"                          