---
  - name: prompt variable
    hosts: all
    vars_prompt: 
      - name: "facts"
        prompt: " Give me a message"
        private: no
    gather_facts: "{{ facts }}"
#    vars:
#      facts: "yes"
    tasks:
      - name: print variable
        debug:
          msg: "{{ facts }}"  