---
  - name: update package on dev servers
    hosts: dev
    gather_facts: yes
    tasks:
      - name: yum update packages on centos
        yum:
          name: "*"
          state: latest
        when: ansible_facts['distribution'] == "CentOS"
          
      - name: apt update packages on ubuntu
        apt:
          name: "*"
          state: latest
        when: ansible_facts['distribution'] == "Ubuntu" 